### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/perfection#1]
# TODO
- [x] Performance test against deque().
- [x] Use a real priority queue and test its performance.
- [x] Implement minimal perfect hashing from random graphs.
- [ ] Redesign API
- [ ] Add optional "index minimization" to Czech hash
- [ ] Add optional "normalization" to Czech hash
- [ ] Make function that outputs C code — make this the main command line function
- [ ] Python 3 compatibility.
- [ ] Performance test for memory using `array()` in strategic places.
